    PROCESSOR 16F887
    #include <p16f887.inc>


__CONFIG _CONFIG1, _INTRC_OSC_NOCLKOUT & _WDT_OFF & _LVP_OFF & _MCLRE_ON 
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
CBLOCK 0x70
    W_TEMP	;0x70
    S_TEMP	;0x71
    LED_POS	;0x72
    COUNTER	;0x73
    ADC_DATA	;0x74
    LED_DATA
   
ENDC
;RESET VECTOR
    ORG     0x00
    GOTO    MAIN_INIT
;INTERRUPT VECTOR
    ORG	    0x04
    MOVWF W_TEMP
    SWAPF STATUS,W
    MOVWF S_TEMP
    
    BCF INTCON,2
    INCF COUNTER,F
    MOVF ADC_DATA,W
    SUBWF COUNTER,W
    BTFSS STATUS,2
    GOTO ISR_EXIT
    CLRF COUNTER
    INCF LED_POS,F
    MOVF LED_POS,W
    CALL LED_PATTERN
    INCF LED_DATA,F
    BANKSEL PORTD
    MOVWF PORTD
    
    
    GOTO ISR_EXIT
    
    
LED_PATTERN:
    ANDLW h'7'
    ADDWF PCL,F
    RETLW b'00000001'	;if W is 0
    RETLW b'00000010'	;if W is 1
    RETLW b'00000100'	;if W is 2
    RETLW b'00001000'	;if W is 3
    RETLW b'00010000'	;if W is 4
    RETLW b'00100000'	;if W is 5
    RETLW b'01000000'	;if W is 6
    RETLW b'10000000'	;if W is 7

ISR_EXIT:
    SWAPF S_TEMP,W
    MOVWF STATUS
    SWAPF W_TEMP,F
    SWAPF W_TEMP,W
    RETFIE    
    
;MAIN CODE
      org 0x60      
MAIN_INIT:
    BANKSEL OSCCON
    MOVLW b'01100111'
    MOVWF OSCCON
    
    BANKSEL ANSEL   ;BANK3
    CLRF ANSEL
    CLRF ANSELH
    
    ;ADC SETUP
    BANKSEL ADCON1
    MOVLW b'00000000'
    MOVWF ADCON1
    BSF ANSEL,0	    ;RA0 as analog
    
    BANKSEL TRISA   ;BANK1
    BSF TRISA,0	    ;RA0 INPUT
    BANKSEL ADCON0
    MOVLW b'01000001'	;fclk/8, SELECT AN0, EN ADC
    MOVWF ADCON0
    ;ADC END
    
    CALL DELAY_10US
    
    ;TIMER2 SETUP
    BANKSEL TRISC    
    BCF TRISC,2	    ;SET RC2 AS OUTPUT FOR THE PWM
    MOVLW h'ff'
    MOVWF PR2	    ;PR2 NOW HOLDS 256
    
    BANKSEL CCP1CON
    MOVLW b'00001100'
    MOVWF CCP1CON
    BSF T2CON,2
    ;TIMER2 END
    
    ;TIMER0 SETUP
    BANKSEL TRISD
    CLRF TRISD
    CLRF COUNTER
    
    BANKSEL PORTD
    CLRF PORTD
    CLRF TMR0
    
    BANKSEL OPTION_REG
    BCF OPTION_REG,5
    BCF OPTION_REG,3
    BCF OPTION_REG,2
    BSF OPTION_REG,1
    BCF OPTION_REG,0
    
    BSF INTCON,7
    BSF INTCON,5
    ;TIMER0 END
    
    ;EUSART SETUP
    BANKSEL TRISC
    BSF TRISC,7
    BSF TRISC,6
    
    BANKSEL BAUDCTL
    BCF BAUDCTL,3
    
    BANKSEL TXSTA
    BCF TXSTA,6
    BCF TXSTA,4
    BSF TXSTA,2
    
    BANKSEL SPBRG
    MOVLW d'25'
    MOVWF SPBRG
    
    BANKSEL RCSTA
    BSF RCSTA,7
    
    BANKSEL TXSTA
    BSF TXSTA,5
    ;EUSART END
    
    GOTO MAIN_LOOP
    
MAIN_LOOP:
    BANKSEL ADCON0
    BSF ADCON0,1
    CALL AN0_WAIT
    CALL DELAY_10US
    CALL LED_LOGIC
    CALL EUSART_WAIT
    GOTO MAIN_LOOP
    
LED_LOGIC:
    MOVLW d'8'
    SUBWF LED_DATA,W
    BTFSS STATUS,2
    RETURN
    CLRF LED_DATA
    RETURN
    
AN0_WAIT:
    BTFSC ADCON0,1
    GOTO AN0_WAIT
    MOVF ADRESH,W
    MOVWF CCPR1L
    MOVWF ADC_DATA
    RETURN
    
DELAY_10US:;SIMPLE 10US DELAY
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    RETURN
    
EUSART_WAIT:
    BANKSEL PIR1
    BTFSS PIR1,4
    GOTO EUSART_WAIT
    BANKSEL TXREG
    MOVF LED_DATA,W
    ADDLW d'48'    

    MOVWF TXREG
    RETURN
END