    PROCESSOR 16F887
    #include <p16f887.inc>


 __CONFIG _CONFIG1, _INTRC_OSC_NOCLKOUT & _WDT_OFF & _LVP_OFF & _MCLRE_ON
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
CBLOCK 0x70
    W_TEMP	;0x70 addr
    S_TEMP	;0x71 addr
    COUNTvar	;0x72 addr
 ENDC
;RESET VECTOR
    ORG     0x00
    GOTO    MAIN_INIT
;INTERRUPT VECTOR
    ORG	    0x04
    ;SWAPPING THE STATUS AND WROKING REGISTERS
    MOVWF W_TEMP
    SWAPF STATUS,W
    MOVWF S_TEMP
    ;DONE WITH SWAP
    
    BCF INTCON,2    ;CLR OVF FLAG MANUALLY
    INCF COUNTvar,F
    MOVLW d'10'
    SUBWF COUNTvar,W
    BTFSS STATUS,2
    GOTO ISR_EXIT
    
    MOVLW b'00010000'
    BANKSEL PORTD   ;INCASE THE BANKS WAS CHANGED
    CLRF COUNTvar
    XORWF PORTD,F
    
ISR_EXIT:
    SWAPF S_TEMP,W
    MOVWF STATUS
    SWAPF W_TEMP,F
    SWAPF W_TEMP,W
    RETFIE
   
;MAIN CODE
      org 0x50      
MAIN_INIT:
    BANKSEL OSCCON
    MOVLW b'01100111'
    MOVWF OSCCON
    
    BANKSEL ANSEL   ;BANK3
    CLRF ANSEL
    CLRF ANSELH
    
    BANKSEL TRISD   ;BANK1
    BCF TRISD,4	    ;SET RD4 TO OUTPUT
    
    ;timer0 setup
    BCF OPTION_REG,5
    BCF OPTION_REG,3
    BSF OPTION_REG,0
    BSF OPTION_REG,1
    BSF OPTION_REG,2	;256 PCS
    
    BSF INTCON,7    ;ENABLE GIE
    BSF INTCON,5    ;OVF IE ENABLE FOR TMR0
    
    BANKSEL PORTD
    CLRF TMR0
    CLRF COUNTvar   ;we will use this address to save the OVF
    CLRF PORTD
MAIN_LOOP:
    
    GOTO    MAIN_LOOP
END