    PROCESSOR 16F887
    #include <p16f887.inc>


__CONFIG _CONFIG1, _INTRC_OSC_NOCLKOUT & _WDT_OFF & _LVP_OFF & _MCLRE_ON 
__CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF

;RESET VECTOR
    ORG     0x00
    GOTO    MAIN_INIT
;INTERRUPT VECTOR
    ORG	    0x04
   
;MAIN CODE
      org 0x60      
MAIN_INIT:
    BANKSEL OSCCON
    MOVLW b'01100111'
    MOVWF OSCCON
    
    BANKSEL ANSEL   ;BANK3
    CLRF ANSEL
    CLRF ANSELH
    ;TIMER 2 SETUP
    BANKSEL TRISC   ;BANK1
    BCF TRISC,2	    ;set RC2 as output
    MOVLW h'ff'
    MOVWF PR2
    
    BANKSEL CCP1CON ;BANK0
    MOVLW b'00001100'	;PWM MODE, SINGLE OUTPUT
    MOVWF CCP1CON
    BSF T2CON,2	    ;TURN TMR2 ON
    
    ;ADC setup
    BANKSEL TRISA
    BSF TRISA,0	    ;SET RA0 AS INPUT
    BANKSEL ANSELH
    BSF ANSEL,0
    BANKSEL ADCON1
    BCF ADCON1,7    ;we want left justified
    BCF ADCON1,5    ;INTERNAL VSS
    BCF ADCON1,4    ;INTERNAL VCC
    BANKSEL ADCON0
    MOVLW b'01000001'
    MOVWF ADCON0
    CALL DELAY_10US
    GOTO MAIN_LOOP
    
MAIN_LOOP:
    BANKSEL ADCON0
    BSF ADCON0,1
    CALL AN0_WAIT
    GOTO MAIN_LOOP
    
DELAY_10US:;SIMPLE 10US DELAY
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    NOP
    RETURN
    
AN0_WAIT:
    BTFSC ADCON0,1
    GOTO AN0_WAIT
    MOVF ADRESH,W
    
    MOVWF CCPR1L
    RETURN
    
END